development:
  adapter: postgresql
  database: makersofbangkok_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: makersofbangkok_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: makersofbangkok_production
  pool: 5
  timeout: 5000
